name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: | 
        cd ./src/GridBot/
        dotnet restore GridBot.sln
    - name: Build
      run: |
        cd ./src/GridBot/ 
        dotnet build GridBot.sln --no-restore
    - name: Test
      run: |
        cd ./src/GridBot/GridBot.Tests
        dotnet test GridBot.Tests.csproj --no-build --verbosity normal
